baseURL = "https://rpetchler.github.io/galant-schemata/"
languageCode = "en-us"
title = "Galant Schemata"

sectionPagesMenu = "main"

[module]
[[module.mounts]]
  source = "site/assets"
  target = "assets"
[[module.mounts]]
  source = "site/content"
  target = "content"
[[module.mounts]]
  source = "site/layouts"
  target = "layouts"
[[module.mounts]]
  source = "site/static"
  target = "static"

[params]
description = "Galant schemata, scores, and data analysis."
authors = "Ross Petchler"
