\version "2.22.2"
\include "../../stylesheets/annotation.ly"
\include "../../stylesheets/score.ly"
\include "../../stylesheets/typography.ly"
\include "1-allegro-di-molto.ly"
\include "2-andante-di-molto.ly"
\include "3-minuetto.ly"
