\version "2.22.2"
\include "../../stylesheets/annotation.ly"
\include "../../stylesheets/score.ly"
\include "../../stylesheets/typography.ly"
\include "1-allegro.ly"
\include "2-andante.ly"
\include "3-tempo-di-menuetto.ly"
